server:
  port: 9090

spring:
  jackson:
    #格式化输出
    serialization.indent_output: true
    #时区
    time-zone: GMT+8

  datasource:

    #数据库驱动
    driverClassName: com.mysql.cj.jdbc.Driver
    #数据库连接
    url: jdbc:mysql://localhost:3307/graduate?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    #数据库用户名
    username: root
    #数据库密码
    password: bjsxt

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#    static-path-pattern: /static/**
#    view:
#      prefix: /templates/
#      suffix: .html
#  thymeleaf:
#    cache: false
#    check-template-location: true
#    encoding: UTF-8
#    mode: HTML5
#    prefix: classpath:/templates/
#    servlet:
#      content-type: text/html
#    suffix: .html


#mybatis配置
mybatis:
  configLocation: classpath:/mybatis-config.xml
  type-aliases-package: edu.zust.se.graduate.entity

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个packaged用逗号或者分号分隔
  typeAliasesPackage: edu.zust.se.graduate.entity
  #枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性
  typeEnumsPackage: edu.zust.se.graduate.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
      #刷新mapper 调试神器
      #    refresh-mapper: true
      #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: F:/git/Git/graduate/files/

alipay:
  appId: 2021000119695452
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCxWNw1kr1HLHqdqPhyGEMTygFKcW/sD6wpBrr8qOutH3J5xLMGFxNuJveA5Za7Gos25ZcGTCUV6JtJ+DGbcN2gZA4dLl7rFgbqNQhzADTLs+L1ILOvrSzT6N0+fDAYkZ9jnr8Em3L+G40cAMYbfk5qiVpcvRgdspoErPX/5ZSVm1U5oD4jsYpUNzM+/OLau76sur89FPdTTzji1cEtxYrFlu4TUaUXvk34Ixv1jP4amQVIBdImImY8xoaDFds56VxXgJwoMCOggELg8E7EQvtZZhuELPc+wchBp8ZMBwROg+xJvMyLCy4x+98h/r/RlQdGHQ1r82uHT1SSkEg4DlzrAgMBAAECggEAVGQmlc+4BjBiQLfxUcm90aLkrloAmmJy2Cr9u9FeJMm8Hbm+Pv2oH1inmkymR27AJGVoUnTViPFhQ/e5E3DH5dT26mfwfwnCTJzj4mWMugply6O+HbDYjhZXga5y7J4PLMaTu0uFkunlYhf0LY0TH5swxsSsvyUIKYVsolLLO80deChHuoCqtz1Z8l/23FPPXlZxd4lNqbOTT6aiWW8HVgSxOh5iYlweRDSz9pa5lVjt2pMPeoPSiFnTj6QxnF414UCTAsaqe6WR5wUK/w++SPONY4OLS0ykHvq7i4pa+V1G5Huu7zbLYdxLvV4MJhsijL5CouSvXgmXES0FCS7VAQKBgQDmw95EmGpXVHRnyR3vS3D39g5S5XA4ksPNOZm3IbWzNoaPDVfj0SygIbNeNVeD1ycUOXXj+6jHDLWvOFxya3Wa40VcpKckJo2+58yuSc7AVCCDY13ZlUu6yBMHYb1141rTu1eAlmUgHHBM1e8gksL+tE9phcAf9dlD3LNhQGTQKwKBgQDEvZY9OjzL/uPmPWUfXAwUbvJMWDY6byswRLnt+PDB1Glo/6Q/dJViYSyCePvNEsdvS8regcosrGS8Wt1i9Qj5Mj7KyjMCLsVFskGrxdZyNgAtgNxkHpXCg+JhYbnyeErlz7NEzn8O6oRqqvCx+gUi2uu0u/ahQyQqRC/Cnf2GQQKBgE+lDGKKZDFt4Zssa5t6YywBjWII9BlidhevqKDvDoIi8IAQ7+Od/xPpbbm3GVRUfpVZW5nq8o54kYA/KJEJC5cAl6Do5xLwB337DMaejLAOmQYf1nVRNMjrYr3qevRkGqX3A7VKsu5JQm0SbSzF2m0EGGBoHC4rsOfeFT8cdW7vAoGACz4ONMd8K+gP29tMSQN4iT5hyC0ORD6QCD0VJt0f3OOndmGNYDboRmvpIDeLpAdbsCdzm01tYSokw4KpvfrknWDap7nwOkKz8Syjhg5TF8mwLul7Lpl001239PqhppJrLUC2LMtkBVUvZe0IvhLcckZyS6ymBkcQ7P1igUuH7kECgYBi5CL+RzEULgOtKpktk8NRjyb2DPKbpaV6b00KVrH5ytq80F0kYcCZkdwXU7XOkHndLEJuguDa5HTdfNvGADWwyaDkAFt4SlSmtw+HPDNE/SakyRrbCgzff9byC2lrEyCQ8jToBPLUkY0upZbtxh4ACrj+rbizTWQbgBHgN8PBOg==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj50M+pt6Rf5GQ22ylMI42cwjyL6pfrhKoKqge6EPLlW6WZ2ApJd8eVWAR+qSTobzeKTKmezkJLAlnnlH5VjlNg+dFyrjblKxX/45u5gcHI+B1L+Bw9ZSy29HW+82rh2yFyfUM/B5Xz0Kf9AZqKpilJapvNhACW1DvRcHGaEnRjKdWiaTkwEW4TkYFSsrkc55sxbqipv8bybBmw34iHRjPj59PyAJX8t6hgyTsXZLuP3QrtIGyqiZmMZD4kA/NEWHxT+n5CjVDmSxtK7afaYvrQzMGN8rixiB1RBAMyf9p0MWVRBewkXcx0zHfdAcz5yFMJpi14NnELZzv4euMXTXYQIDAQAB
  notifyUrl: http://d2zbcq.natappfree.cc/alipay/notify